name: Deploy Checkly Checks

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  deploy-checks:
    runs-on: ubuntu-latest
    name: Deploy checks to Checkly
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Deploy checks to Checkly
        uses: checkly/github-actions@v1
        with:
          command: 'deploy'
        env:
          CHECKLY_API_KEY: ${{ secrets.CHECKLY_API_KEY }}
          CHECKLY_ACCOUNT_ID: ${{ secrets.CHECKLY_ACCOUNT_ID }}
